swagger: '2.0'
info:
  version: "1.0.0"
  title: Persian Api
  description: Move your app forward with the Persian Api
  termsOfService: http://persianapi.herokuapp.com/terms.html
  contact:
    name: Saeed Esfandi
    email: saeed.esfandi@gmail.com
    url: https://ir.linkedin.com/in/saeedesfandi
  license:
    name: MIT
    url: http://opensource.org/licenses/MIT

host: persianapi.herokuapp.com
basePath: /v1
schemes:
  - https

consumes:
  - application/json
produces:
  - application/json

paths:
  /:
    get:
      summary: Root
      description: Returns Welcome to user
      tags:
        - Root
      responses:
        200:
          description: OK
  /services:
    get:
      summary: Services List
      description: Returns all services from the system that the user has access to
      tags:
        - Services
      responses:
        200:
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/Service'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
  /services/{id}:
    parameters:
      - name: id
        in: path
        description: ID
        type: string
        required: true
    get:
      summary: Service Options
      description: Returns service options
      tags:
        - Services
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/Service'
        404:
          description: Not Found
          schema:
            $ref: '#/definitions/Error'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'

definitions:
  Service:
    type: object
    properties:
      id:
        type: string
        description: id
      description:
        type: string
        description: Description of service.
  Error:
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
      fields:
        type: string
