swagger: '2.0'
info:
  version: "1.0.0"
  title: Persian Api
  description: Move your app forward with the Persian Api
  termsOfService: http://persianapi.herokuapp.com/terms.html
  contact:
    name: Saeed Esfandi
    email: saeed.esfandi@gmail.com
    url: http://cse.shirazu.ac.ir/~esfandi
  license:
    name: MIT
    url: http://opensource.org/licenses/MIT

host: persianapi.herokuapp.com
basePath: /v1
schemes:
  - http
  - https

consumes:
  - application/json
produces:
  - application/json

paths:
  /:
    get:
      description: Returns Welcome to user
      responses:
        200:
          description: OK
  /services:
    get:
      description: Returns all services from the system that the user has access to
      responses:
        200:
          description: OK
  /services/{id}:
    parameters:
      - name: id
        in: path
        description: ID
        type: string
        required: true
    get:
      description: Returns service options
      responses:
        200:
          description: OK
        404:
          description: Not Found
