# PostgreSQL. Versions 9.1 and up are supported.
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: persianapi
  username: persianapi
  password: persianapi
  #host: localhost
  #port: 5432
  #schema_search_path: myapp,sharedapp,public
  #min_messages: notice

test:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
  #database: persianapi_test

#   DATABASE_URL="postgres://myuser:mypass@localhost/somedatabase"
production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
  #database: database
  #username: username
  #password: <%= ENV['PERSIANAPI_DATABASE_PASSWORD'] %>
